CREATE TABLE boardroom (
	id      INTEGER      NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name    VARCHAR(255) NOT NULL,
	created TIMESTAMP    NOT NULL DEFAULT now(),
	updated TIMESTAMP    NOT NULL DEFAULT now() ON UPDATE now()
)

ENGINE = InnoDB;
